apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: db-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db/data"
